<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="homenew.aspx.cs" Inherits="QAProject.homenew" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="home.css" />
    <title></title>
</head>
<body>
      <nav class="navbar navbar-light bg-light">
         <h1 class="text-success rounded float-start">COLOMBO</h1>
         <img class="rounded mx-auto d-block" src="logo.png" />
        <h1 class="text-success rounded float-end">MUNICIPAL COUNCIL</h1>
        
     
  <div class="container">
     
  </div>
</nav>
     
  <nav class="green navbar navbar-expand-lg navbar-light bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="https://localhost:44302/homenew.aspx" style="color:white">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#aboutus">About us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="#contactus">Contact us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="https://localhost:44302/collectingspot.aspx">Garbage collecting spot</a>
        </li>

        <li class="nav-item dropdown float-end">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Login/Register
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="https://localhost:44302/login.aspx">GTF Member</a></li>
            <li><a class="dropdown-item" href="https://localhost:44302/stafflogin.aspx">Staff</a></li>
            
          </ul>
        </li>
       
      </ul>
      
    </div>
  </div>
</nav>
     <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="cmc1.jpg" class="d-block w-100 h-50" alt="..."/>
    </div>
    <div class="carousel-item">
      <img src="cmcnew.jpg" class="d-block w-100" alt="..."/>
    </div>
    <div class="carousel-item">
      <img src="75.jpg" class="d-block w-100" alt="..."/>
    </div>
  </div>
</div>
    <br />
    <form id="form1" runat="server">
  <center>
    <div class="container">
       <h1>Make Colombo beautiful</h1>
        <div class="row row-cols-1 row-cols-md-5 g-6">
            <asp:Repeater ID="repeater" runat="server" OnItemCommand="repeater_ItemCommand">
                <ItemTemplate>
                    <div class="col ps-3 pr-5">
                        <div class="card" style="width:18rem">
                            <img src='<%# Eval("Poster") %>' class="card-img-top mh-25" alt="..." />
                        </div>
                    </div>
                </ItemTemplate>
            </asp:Repeater>
        </div>
    </div>
</center>

    </form>
    
<br /><br />
   

<section>

<center><div class="card mb-3" style="max-width: 540px;" id="aboutus">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="logo cmc.jpg" class="img-fluid rounded-start" alt="..."/>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">About us</h5>
        <p class="card-text">Garbage collection is the process of collecting, transporting, and disposing of waste materials generated by households, businesses, and other entities. This process is crucial for maintaining clean and healthy environments, preventing pollution and diseases, and preserving natural resources. Garbage collection services are typically provided by local governments or private waste management companies, who use specialized vehicles and equipment to collect and transport the waste to designated disposal sites, such as landfills or recycling facilities. The collection schedule and fees may vary depending on the location and type of service, but in general, garbage collection is an essential service that plays a critical role in maintaining the quality of life for communities.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div></center>
</section>
    <br />

  <section id="contactus">
     <h1>Contact us</h1>
 <br />
               <div class="d-flex justify-content-center">
                <div class="card text-bg-secondary mb-3 me-5" style="max-width: 25rem;height:13rem">
                <div class="card-header">MARKETING & ADVERTISING</div>
                <div class="card-body">
                    <h5 class="card-title"><img src="call.png" width="30"height="30"/>&nbsp;0715876693-Colombo</h5><br/>
                    <p class="card-text"><img src="mail.png" width="30" height="30"/>&nbsp;marketing@muncipal@gmail.com</p>
                </div>
                </div>
                <div class="card text-bg-secondary mb-3 me-5" style="max-width: 25rem;;height:13rem">
                <div class="card-header">IT DEPARTMENT</div>
                <div class="card-body">
                    <h5 class="card-title"><img src="call.png" width="30"height="30"/>&nbsp;0112811875</h5><br/>
                    <p class="card-text"><img src="mail.png" width="30" height="30"/>&nbsp;MunicipalIT@gmail.com</p>
                </div>
                </div>
                <div class="card text-bg-secondary mb-3 me-5" style="max-width: 25rem;;height:13rem">
                <div class="card-header">HELP DESK</div>
                <div class="card-body">
                    <h5 class="card-title"><img src="call.png" width="30"height="30"/>&nbsp;(09.00am-06.00pm Monday-Friday)<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0112056089/0704469231</h5><br>
                    <p class="card-text"><img src="mail.png" width="30" height="30"/>&nbsp;helpdesk@colombomunicipal.com</p>
                </div>
                </div>
            </div>
        </section>


  

 <footer>
   
    <div class="feedback d-flex justify-content-center ">
         <h4 >Feedback</h4>
        <img src="fb.png" style="width:25px;border-radius:20px;margin:0px 10px" />
        <img src="in.jpg" style="width:20px;border-radius:20px;margin:0px 10px"/>
        
       
     </div>
                     <center><p style="color:white">Privacy policy &nbsp; &nbsp; &nbsp; &nbsp; Terms and conditions</p></center>
                <center><p style="color:white">&copy;2023 Garbage |Site map|Enviromental Surchagers. </p></center>

                  
      
     

         
               

 </footer>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>


</body>
</html>
